### ISSUE TITLE
Questions about the format of the dataset

### ISSUE THREAD

**Issue by yaoshanliang** [yizhou-wang/RODNet#19]
I have downloaded the dataset from your website. The format is shown below.
![image](https://user-images.githubusercontent.com/5028569/115231551-49a1f480-a148-11eb-8e37-a9d51cb43b7b.png)

In file cruw_devkit_tutorial_rod2021.ipynb, the format is
![image](https://user-images.githubusercontent.com/5028569/115231599-54f52000-a148-11eb-82a1-43b5e7a578aa.png)

Do I need to transfer the downloaded dataset into the format in the ipynb file?
Is the transfer script already provided?

**Comment by yaoshanliang** [comment]
@yizhou-wang

**Comment by yizhou-wang** [comment]
Hi @yaoshanliang, what you need to do is to put the files according to the file structure shown in the ipynb file. You do not need to use any scripts.
