### ISSUE TITLE
About prepare.dataset.py --configs file

### ISSUE THREAD

**Issue by xiaoyangxxx** [yizhou-wang/RODNet#20]
HI！
    When I run tools/prepare_dataset/prepare_data.py \
                --config configs/config_rodnet_cdc_win16.py \  
     There is always an error：in the load_configs.py import_module.No module name config_rodnet_cdc_win16。
It is confusing whether the configs file should not be set to this. @yizhou-wang I sincerely hope you can help me。

**Comment by yizhou-wang** [comment]
config_rodnet_cdc_win16.py is located in the folder config. Please make sure you have input the correct file path.
