### ISSUE TITLE
Questions about confmap

### ISSUE THREAD

**Issue by songsanling** [yizhou-wang/RODNet#26]
For ConfMaps generated from CRF annotation:
confmap_sigmas   {'pedestrian': 15, 'cyclist': 20, 'car': 30}; confmap_sigmas_interval  {'pedestrian': [5, 15], 'cyclist': [8, 20], 'car': [10, 30]}; confmap_length  {'pedestrian': 1, 'cyclist': 2, 'car': 3}
What do these items mean and why to choose these values? I read [48] but did not get a clue. Thanks.

**Comment by yizhou-wang** [comment]
Duplicate of #9 

`confmap_sigmas` are the variances of different objects. 
`confmap_length` are the rough lengths of different objects.
They are empirically defined.
