### ISSUE TITLE
Questions about radar data files in the dataset

### ISSUE THREAD

**Issue by chunguangqu** [yizhou-wang/RODNet#29]
Hi,
    Can you introduce the radar data in the dataset? For example, what does the 2 in the shape 128*128*2 in a single npy file mean? What does it mean that the radar data corresponding to each image is 4 npy files? Thanks for your answer

**Comment by yizhou-wang** [comment]
Hi! The two channels are real and imaginary parts of the values after FFTs. The 4 npy files are radar chirps in each frame. Here, the four chirps are uniformly sampled from the raw data.

Similar question also mentioned here: https://github.com/yizhou-wang/cruw-devkit/issues/10
