### ISSUE TITLE
'annotation' folder is missing under cruw folder

### ISSUE THREAD

**Issue by jb892** [yizhou-wang/RODNet#3]
Hi Yizhou,

I'm testing your `prepare_data.py` script to generate tranining data. However, it throws out some error at the following line:
https://github.com/yizhou-wang/RODNet/blob/969cad6f08b8957b26bc16f86ac4e835d1294050/tools/prepare_dataset/prepare_data.py#L10

I guess you have forgotten to put the `annotation` folder under cruw project.
![Screen Shot 2021-01-18 at 17 28 42](https://user-images.githubusercontent.com/5748897/104897131-f8e8f700-59b2-11eb-9355-51315f96680d.png)

**Comment by yizhou-wang** [comment]
Hi @jb892, 
The annotation package has been merged to the master branch. Please check yizhou-wang/cruw-devkit#2. Thanks for pointing out the mistake!

**Comment by jb892** [comment]
Thx
