### ISSUE TITLE
can't create the test.pkl

### ISSUE THREAD

**Issue by xiaoche-24** [yizhou-wang/RODNet#33]
After reviewing previous questions and answers, I tried to modify prepare.py, but test.pkl still cannot be generated .Can you help me? pls...

**Comment by yizhou-wang** [comment]
I have just updated the [script](https://github.com/yizhou-wang/RODNet/commit/7c3fd6f996f1f3699e5131b0312a770c8896fcb2) to handle the situation when camera images are not available.
