### ISSUE TITLE
Using processed pointclouds from Radar data

### ISSUE THREAD

**Issue by YoushaaMurhij** [yizhou-wang/RODNet#41]
I have a question about the ability to use  the received radar point clouds from raw radar data as an input to your model. 
Is it possible here?  Any suggestions?

Thanks!

**Comment by yizhou-wang** [comment]
The short answer is No.

One of the strengths of the RODNet is to extract features from radar frequency (RF) for object detection (especially for classification). With sparse radar point cloud (unlike LiDAR point cloud), it is very hard to accomplish this task. However, if you can have denser radar point clouds (using different radar sensors), you may use the lidar point cloud method for object detection. Point cloud and RF images should belong to two different tasks.
