### ISSUE TITLE
关于测试集的ground truth

### ISSUE THREAD

**Issue by Strongly20** [yizhou-wang/RODNet#44]
您好~感谢您提供的代码和数据集，请问测试集有对应的标注吗？因为最近我在调试AP和AR的评估代码没有找到truth_dir的路径，另外您最新上传的convert_rodnet_to_rod2021.py是为了将test.py生成的.txt格式与标注格式相同吗？因为我看之前生成的与训练中的anno文件顺序不太一样。
期待您的回复！

**Comment by yizhou-wang** [comment]
Duplicated of https://github.com/yizhou-wang/cruw-devkit/issues/12. 

Closed.
