### ISSUE TITLE
Compile pip install -e . with error

### ISSUE THREAD

**Issue by rong-xue** [yizhou-wang/RODNet#45]
pip install -e reports an error. According to the online solution is not solved, help!The following screenshots of the error are attached, without the screenshots of Requirement already satisfied and Warning!
![微信图片_20220316151401](https://user-images.githubusercontent.com/78159335/158536207-2dc7f8da-3621-4cbe-9977-f97fdfc798e1.png)

**Comment by yizhou-wang** [comment]
Could you please provide the full error message? I cannot know the reason for your error from this screenshot.

**Comment by rong-xue** [comment]
我把terminal的内容保存为word文档和mark文档了，您可以看看！还需要什么，我再给你，麻烦您了！
[RODNet.docx](https://github.com/yizhou-wang/RODNet/files/8260266/RODNet.docx)
[截图.md](https://github.com/yizhou-wang/RODNet/files/8260268/default.md)

**Comment by rong-xue** [comment]
我将terminal的内容及自己的一些步骤复制到mark文件中了，看起来可能比word会好一些！我自己目前也不知是什么问题，不知道如何解决，因此多麻烦您了！下面附上了项目结构图！
[rodnet.md](https://github.com/yizhou-wang/RODNet/files/8260553/rodnet.md)
![项目截图](https://user-images.githubusercontent.com/78159335/158557342-697dbb15-f2a1-4946-b5ee-39cf9f266720.png)

**Comment by yizhou-wang** [comment]
Are you using the TDC module or not? If you are using TDC, please use CUDA=10.1 and pytorch=1.4 as mentioned in readme.

**Comment by rong-xue** [comment]
I followed the steps and chose to not use TDC. Enter the following statement.
conda install pytorch torchvision cudatoolkit=10.1 -c pytorch  # if not using TDC.
In this case, I just changed cudatoolkit=10.1 to 10.2.
Do I need to use TDC, rebuild the environment and try again. Previously I chose not to use TDC, but only distinguished it by the above statement, I don't know if there is any other way to distinguish it.
![TDC](https://user-images.githubusercontent.com/78159335/158770778-980ccbfa-3401-44b0-80fb-fc5e47094752.png)
.

**Comment by yizhou-wang** [comment]
From the log you sent me through email, you were compiling TDC. Please make sure you follow the steps. 

BTW, we previously did not set up the environment in Windows, but that should not be a problem.

**Comment by rong-xue** [comment]
Okay, thank you! I'll rebuild the environment and try again with the corresponding version. You have not set up the environment in Windows, if possible, can you tell me on what system or software the environment is configured?

**Comment by yizhou-wang** [comment]
I think the configurations and environment are mentioned in the readme. We only tested on ubuntu 16, 18, and 20.
