### ISSUE TITLE
about load_txt.py

### ISSUE THREAD

**Issue by Strongly20** [yizhou-wang/RODNet#47]
您好，最近我在尝试通过代码和之前您在CRUW问题5中提供的网址理解AP的计算，但是看到read_rodnet_res函数第133行这里不太理解，为什么设置if agl > math.radians(60) or agl < math.radians(-60):，这是根据测试集的先验信息设置的吗？ 提前感谢您的回答！

**Comment by yizhou-wang** [comment]
That is the FOV during the evaluation. We will not evaluate the detection outside that angle range.
