### ISSUE TITLE
configuration file

### ISSUE THREAD

**Issue by rong-xue** [yizhou-wang/RODNet#52]
--config configs/<CONFIG_FILE> What is the configuration file in the command, I have tried many times and got an error, I would like to ask for the solution!
![图片](https://user-images.githubusercontent.com/78159335/163705903-4aa31f2f-4ed4-4008-88f0-6cdaa23dcd33.png)

**Comment by yizhou-wang** [comment]
<CONFIG_FILE> is the configuration files in configs folder.
<DATASET_ROOT> is the root folder you put the dataset.
