### ISSUE TITLE
tools/test.py出现keyError

### ISSUE THREAD

**Issue by lightzwc** [yizhou-wang/RODNet#53]
你好，我运行这个命令的时候，
python tools/test.py --config configs/config_rodnet_cdc_win16.py --data_dir ./data/result/ --checkpoint checkpoints/rodnet-cdc-win16-wobg-20220419-105954/epoch_100_final.pkl --res_dir results/
（data/result文件夹是我生成的train和test的pkl文件）
出现这个问题，
Traceback (most recent call last):
  File "tools/test.py", line 184, in <module>
    data = data_dict['radar_data']
KeyError: 'radar_data'
python tools/test.py --config configs/config_rodnet_cdc_win16.py --data_dir ./data/result/ --checkpoint checkpoints/rodnet-cdc-win16-wobg-20220419-105954/epoch_100_final.pkl --res_dir results/

**Comment by rong-xue** [comment]
您好，我看您进行到test.py这一步，可以请问一下python tools/prepare_dataset/prepare_data.py这一命令怎么输入，我尝试了很多次都失败了，目前没有弄懂什么原因！
![image](https://user-images.githubusercontent.com/78159335/164168673-c43af3b7-92b9-4e59-a915-ecdb106ab72a.png)

**Comment by lightzwc** [comment]
> 您好，我看您进行到test.py这一步，可以请问一下python tools/prepare_dataset/prepare_data.py这一命令怎么输入，我尝试了很多次都失败了，目前没有弄懂什么原因！ ![image](https://user-images.githubusercontent.com/78159335/164168673-c43af3b7-92b9-4e59-a915-ecdb106ab72a.png)

你好，请参考
python tools/prepare_dataset/prepare_data.py --config configs/config_rodnet_cdc_win16.py --data_root data_root/ --split train,test --out_data_dir data/result

**Comment by lightzwc** [comment]
路径问题，已解决

**Comment by xuezhen5267** [comment]
能问一下楼上，问题如何解决的？我也有同样的报错，路径哪里有问题？

**Comment by lightzwc** [comment]
![1651648535](https://user-images.githubusercontent.com/49677654/166637222-d3799414-c346-4ce5-940f-fdbb0eb166a4.jpg)
加上自己radar npy文件的绝对路径，不然读取不到数据文件。

**Comment by Heng-Dickens** [comment]
请问有修改这个文件的详细信息吗？我也遇到了同样的问题不知道如何解决，我不清楚你指的npy文件是哪些文件？

**Comment by ZhongKang97** [comment]
![image](https://user-images.githubusercontent.com/47888587/232264939-04bae2f8-5565-4d18-850d-17fb2f5a4950.png)
should not end with "/" ,or it will cause wrong path when loading data from the the pkl file ,like this 
![image](https://user-images.githubusercontent.com/47888587/232265043-a70b755d-ba82-4006-9f38-7282ac0c4f72.png)
![image](https://user-images.githubusercontent.com/47888587/232265173-b959149b-ab28-4a00-b03c-3ad4ad1528e0.png)
