### ISSUE TITLE
How to conduct the angle FFT？

### ISSUE THREAD

**Issue by leo038** [yizhou-wang/RODNet#62]
The angle FFT is conducted along the different receivers antennas, for example, if there are 8 virtual antennas , dose it mean a 8 points FFT is conduct?

**Comment by leo038** [comment]
Sure we can do a FFT more than 8 points, but the  length of angle in time domain is 8 points?

**Comment by leo038** [comment]
@yizhou-wang

**Comment by yizhou-wang** [comment]
Please find code for angle FFT here: https://github.com/Xiangyu-Gao/mmWave-radar-signal-processing-and-microDoppler-classification.

Duplicate of #40
