### ISSUE TITLE
How is the variance for each class calculated

### ISSUE THREAD

**Issue by zhengzangw** [yizhou-wang/RODNet#9]
Although discussed in #2, I am still confused about how variance is computed. In the paper, it says "the variance is related to the object class and scale information", while in the code, `sigma` is calculated by

https://github.com/yizhou-wang/RODNet/blob/969cad6f08b8957b26bc16f86ac4e835d1294050/rodnet/core/confidence_map/generate.py#L36

As I understand, `sigma` is the class-specific variance, and `confmap_sigma` is a hyper-parameter for variance per class. My question is:

- Is there a physical meaning or intuition behind `np.arctan(confmap_length[class_name] / (2 * range_grid[rng_idx]))`
- Is `confmap_sigmas`, `confmap_sigmas_interval` and `confmap_length` all hyper-parameters choosed via experiments?

Thanks in advance!

**Comment by yizhou-wang** [comment]
The intuition behind this formula is that `sigma` is approximating the reflection surface size at different distances/scales. This formula as well as the hyper-parameters you mentioned above is empirically defined.

**Comment by zhengzangw** [comment]
Thanks!
